// <auto-generated />
using System;
using ApiMatheus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMatheus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiMatheus.Models.Convidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PresenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PresenteId");

                    b.ToTable("Convidados");
                });

            modelBuilder.Entity("ApiMatheus.Models.Presente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PessoaConfirmada")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Presentes");
                });

            modelBuilder.Entity("ApiMatheus.Models.Convidado", b =>
                {
                    b.HasOne("ApiMatheus.Models.Presente", "Presente")
                        .WithMany()
                        .HasForeignKey("PresenteId");

                    b.Navigation("Presente");
                });
#pragma warning restore 612, 618
        }
    }
}
